package com.telit.zhkt_three.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.telit.zhkt_three.JavaBean.HomeWorkAnswerSave.AnswerItemListConverter;
import java.util.List;

import com.telit.zhkt_three.JavaBean.FillBlankBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FILL_BLANK_BEAN".
*/
public class FillBlankBeanDao extends AbstractDao<FillBlankBean, String> {

    public static final String TABLENAME = "FILL_BLANK_BEAN";

    /**
     * Properties of entity FillBlankBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property List = new Property(1, String.class, "list", false, "LIST");
    }

    private final AnswerItemListConverter listConverter = new AnswerItemListConverter();

    public FillBlankBeanDao(DaoConfig config) {
        super(config);
    }
    
    public FillBlankBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FILL_BLANK_BEAN\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"LIST\" TEXT);"); // 1: list
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FILL_BLANK_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FillBlankBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        List list = entity.getList();
        if (list != null) {
            stmt.bindString(2, listConverter.convertToDatabaseValue(list));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FillBlankBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        List list = entity.getList();
        if (list != null) {
            stmt.bindString(2, listConverter.convertToDatabaseValue(list));
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public FillBlankBean readEntity(Cursor cursor, int offset) {
        FillBlankBean entity = new FillBlankBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : listConverter.convertToEntityProperty(cursor.getString(offset + 1)) // list
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FillBlankBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setList(cursor.isNull(offset + 1) ? null : listConverter.convertToEntityProperty(cursor.getString(offset + 1)));
     }
    
    @Override
    protected final String updateKeyAfterInsert(FillBlankBean entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(FillBlankBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FillBlankBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
